/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#7f57f1",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Neumorphic color palette
        "neomorphic-bg": "var(--neomorphic-bg)",
        "neomorphic-surface": "var(--neomorphic-surface)",
        "neomorphic-surface-dark": "var(--neomorphic-surface-dark)",
        "neomorphic-surface-light": "var(--neomorphic-surface-light)",
        "neomorphic-text": "var(--neomorphic-text)",
        "neomorphic-text-light": "var(--neomorphic-text-light)",
        "neomorphic-text-muted": "var(--neomorphic-text-muted)",
        "neomorphic-primary": "var(--neomorphic-primary)",
        "neomorphic-primary-light": "var(--neomorphic-primary-light)",
        "neomorphic-primary-dark": "var(--neomorphic-primary-dark)",
        "neomorphic-accent": "var(--neomorphic-accent)",
        "neomorphic-accent-light": "var(--neomorphic-accent-light)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        'neomorphic': '20px',
        'neomorphic-sm': '12px',
        'neomorphic-lg': '32px',
      },
      boxShadow: {
        'neomorphic': '8px 8px 16px var(--shadow-dark), -8px -8px 16px var(--shadow-light)',
        'neomorphic-sm': '4px 4px 8px var(--shadow-dark), -4px -4px 8px var(--shadow-light)',
        'neomorphic-lg': '12px 12px 24px var(--shadow-dark), -12px -12px 24px var(--shadow-light)',
        'neomorphic-xl': '16px 16px 32px var(--shadow-dark), -16px -16px 32px var(--shadow-light)',
        'neomorphic-inset': 'inset 4px 4px 8px var(--shadow-inset-dark), inset -4px -4px 8px var(--shadow-inset-light)',
        'neomorphic-hover': '12px 12px 20px var(--shadow-dark), -12px -12px 20px var(--shadow-light)',
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
  plugins: [require("tailwindcss-animate"),
  require('daisyui'),],
}